% Get the current directory of this file
folderPath = fileparts(mfilename('fullpath'));

% Get the name of the folder
[~, folderName] = fileparts(folderPath);

% open the figure with the name of the folder
open(fullfile(folderPath, [folderName '.fig']));
fig = gcf;

set(fig, 'Position', [100, 100, 330, 500]);

% Export with matlab to svg
saveas(fig, fullfile(folderPath, [folderName '_matlab.svg']), 'svg');

% Call the function Plot2LaTeX to convert the figure to a svg file
fileName = fullfile(folderPath, [folderName,'_latex']);
Plot2LaTeX(fig, fileName, 'FontSize', 10, 'SquishedText',true, 'ReplaceList',...
  {'xlabel1', 'time / s';...
   'xlabel2', 'time / s';...
   'xlabel3', 'time / s';...
   'xlabel4', 'time / s';...
   'xlabel5', 'time / s';...
   'ylabel1', 'v / $\frac{\text{m}}{\text{s}}$';...
   'ylabel2', '$\mathrm{\omega}$ / rpm';...
   'ylabel3', 'P / W';...
   'ylabel4', '$\mathrm{\theta}$ / $^{\circ}$';...
   'ylabel5', 'T / N m';...
   'vc', '$v_c$';...
   'vh', '$v_h$'})

close(fig)